### PR TITLE
Cleanup old binaries

### PR DESCRIPTION
**Pull request by rabi**
There could be older version of the binaries that would mess up things.

### CODE REVIEW

**Comment by dprince** [comment]
would this cause the binaries to be downloaded each time though?

**Comment by rabi** [comment]
> would this cause the binaries to be downloaded each time though?

Yes. We can check for the existing version before downloading though. However, we already clean/download for other binaries[1] and probably is not a big overhead.


[1] https://github.com/openstack-k8s-operators/keystone-operator/blob/master/Makefile#L189

**Comment by dprince** [comment]
> > would this cause the binaries to be downloaded each time though?
> 
> Yes. We can check for the existing version before downloading though. However, we already clean/download for other binaries[1] and probably is not a big overhead.
> 
> [1] https://github.com/openstack-k8s-operators/keystone-operator/blob/master/Makefile#L189

I'm not sure I agree we should be doing that. (we should remove the cleaning of kustomize each time!)

Rather than cleaning these each time, and forcing users to download could we could add a cleanup Makefile target and let folks call that if they wish.

**Comment by rabi** [comment]
> Rather than cleaning these each time, and forcing users to download could we could add a cleanup Makefile target and let folks call that if they wish.

Well, as I mentioned earlier user won't even realize that they have an old binary and would 'whish' to download. PRs would be changed to use old one[1]. But I can't argue enough about this inconvenience.

[1] https://github.com/openstack-k8s-operators/keystone-operator/pull/162#discussion_r1094328439

**Pull request closed without merging**
