### PR TITLE
Use 'PatchInstance' from lib-common

### PR DESCRIPTION
**Pull request by abays**

### CODE REVIEW

**Review by stuggi — APPROVED** [review]
/lgtm

**Comment by abays** [comment]
This is failing CI due to the `Github rate-limiter failed the request. Either authenticate or wait a couple of minutes.` error.  So not an actual problem with the PR.

**Review by gibizer — APPROVED** [review]
/lgtm

**Comment by gibizer** [comment]
https://github.com/openstack-k8s-operators/keystone-operator/actions/runs/3875934147/jobs/6619580290 fails due to login failure to the OCP cluster during test.

**Pull request merged**
