### PR TITLE
Use pre-created osp-secret in kuttl tests

### PR DESCRIPTION
**Pull request by kajinamit**
Now install_yamls creates the global osp-secret in the namespace where kuttl tests run. This replaces the specific secret created for tests to and make that global secret used consistently.

This also removes the step to clean up existing KeystoneAPI CR, because kuttl targets now contains the required cleanup steps.

### CODE REVIEW

**Comment by kajinamit** [comment]
/test keystone-operator-build-deploy-kuttl

503 while downloading telemetry-operator image

**Review by abays — APPROVED** [review]
Tested locally

/lgtm

**Pull request merged**
