### PR TITLE
Prohibit updating spec.databaseInstance

### PR DESCRIPTION
**Pull request by kajinamit**
Updating spec.databaseInstance does not migrate existing data to a new instance and can break resource access unexpectedly. This prohibits such update.

### CODE REVIEW

**Comment by abays** [comment]
I wonder if the new "immutable" tag available in Kubernetes 1.25+ would be cleaner here.  An example can be found here [1].  While in this example they're making the whole CRD immutable, I think you can apply the `kubebuilder` annotation to just one particular field.

[1] https://blog.rewanthtammana.com/kubernetes-crd-validation-with-cel-and-kubebuilder-marker-comments#heading-crd-validation-in-kubernetes-125

**Comment by kajinamit** [comment]
Yeah using that validation feature can be much simpler. The only concern is that the feautre is still in beta state since it was promoted at 1.25, afaik.

**Pull request closed without merging**
