### PR TITLE
Render service config in operator and store in secret

### PR DESCRIPTION
**Pull request by stuggi**
Removes the need of an init container, renders all configs in go and stores the resulting configs on a secret.

### CODE REVIEW

**Review by olliewalsh — APPROVED** [review]
/lgtm

**Comment by stuggi** [comment]
error: unable to create the debug pod "oko-03-9f2sl-master-0-debug-c4pqb"
make: *** [Makefile:517: crc_storage] Error 1
+ n=3
+ ((  n >= retries  ))
+ echo 'Failed to run '\''make crc_storage'\'' target. Aborting'
Failed to run 'make crc_storage' target. Aborting
+ exit 1

**Pull request merged**
