### PR TITLE
On reconcileDelete - remove db finalizer first

### PR DESCRIPTION
**Pull request by pinikomarov**
continuing [pr 89](https://github.com/openstack-k8s-operators/keystone-operator/pull/89) that got messy and closed for some reason ..

On 	reconcileDelete remove db finalizer before the keystone one

### CODE REVIEW

**Comment by pinikomarov** [comment]
@abays @stuggi Hi guys , please give this an ok-to-test

**Comment by stuggi** [comment]
you miss the go.mod change. you don't have to open a new PR to squash commits. just do `git rebase -i HEAD~10` or any number of commits you have and then mark those to squash.

**Comment by pinikomarov** [comment]
@stuggi @gibizer I do you have any idea what the opeartor-lint gate is breaking about ?  (error below)
I don't see any dup entries in go.mod and with go.sum I reran go mod tidy..am I'm missing something ? 
` Error: ../../../go/pkg/mod/golang.org/x/oauth2@v0.2.0/google/default.go:17:2: ambiguous import: found package cloud.google.com/go/compute/metadata in multiple modules:
	cloud.google.com/go/compute v1.7.0 (/home/runner/go/pkg/mod/cloud.google.com/go/compute@v1.7.0/metadata)
	cloud.google.com/go/compute/metadata v0.2.0 (/home/runner/go/pkg/mod/cloud.google.com/go/compute/metadata@v0.2.0)`

**Comment by gibizer** [comment]
> @stuggi @gibizer I do you have any idea what the opeartor-lint gate is breaking about ? (error below) I don't see any dup entries in go.mod and with go.sum I reran go mod tidy..am I'm missing something ? ` Error: ../../../go/pkg/mod/golang.org/x/oauth2@v0.2.0/google/default.go:17:2: ambiguous import: found package cloud.google.com/go/compute/metadata in multiple modules: cloud.google.com/go/compute v1.7.0 (/home/runner/go/pkg/mod/cloud.google.com/go/compute@v1.7.0/metadata) cloud.google.com/go/compute/metadata v0.2.0 (/home/runner/go/pkg/mod/cloud.google.com/go/compute/metadata@v0.2.0)`

This is not operator-lint specific the `make vet` target also fails for me with the same error on your PR. It passes on master though. So we need to figure out what causing the dependency conflict in your PR

**Comment by stuggi** [comment]
The issue is that your patch updates golang.org/x/oauth2 to use v0.2.0 . I have not found a dependency which requires this. if I delete that from go.mod and run `go mod tidy` it won't update to v0.2.0. please try the same. maybe run `go clean -modcache` to clean your local mod cache before doing that.

**Comment by pinikomarov** [comment]
@stuggi thanks I returned oauth to it's original version, now all lint are ok .
unrelated:
 - " 1 workflow awaiting approval " what does that mean ?  is that the commit to downstream for testing and merge ?
- an ok-to-test can be given once in a patch and the rest of the updates are all ok to test from there on right ? i.e. do you have to give several ok-to-test ?

**Comment by stuggi** [comment]
> @stuggi thanks I returned oauth to it's original version, now all lints seem ok .
> 
> unrelated:
> 
> * " 1 workflow awaiting approval " what does that mean ?  is that the commit to downstream for testing and merge ?
> * an ok-to-test can be given once in a patch and the rest of the updates are all ok to test from there on right ? i.e. do you have to give several ok-to-test ?

depending on the change another ok-to-test  is required or the PR approved by a maintainer.

**Review by stuggi — APPROVED** [review]
/lgtm

**Pull request merged**
