### PR TITLE
Remove log_config_append from keystone config

### PR DESCRIPTION
**Pull request by cescgina**
The log_config_append line in the template keystone.conf seems to
interfere with normal config handling and prevents debug settings
introduced from keystone.conf.d/custom.conf which are sent through the
customServiceConfig field in KeystoneAPI. If the log_config_append
option is set in the keystone.conf template is set and debug = true is
set in custom.conf, then the custom.conf config is ignored and no debug
logs are shown.

### CODE REVIEW

**Comment by abays** [comment]
Could this cause any side effects we are not anticipating?

**Comment by cescgina** [comment]
> Could this cause any side effects we are not anticipating?

Logs look normal, what we had before + DEBUG logs, but I don't know enough about keystone config to know for sure.

**Comment by dprince** [comment]
I think we could probably remove this from the config by we probably want to replace it with something that logs to stdout right? It looks like including /etc/keystone/logging.conf setups default *file* logging.

**Review by rabi — CHANGES_REQUESTED** [review]
Yeah, we don't need that as default (which is to redirect to a separate logging configuration file) . But there are more changes required. Please check https://github.com/openstack-k8s-operators/ironic-operator/commit/d9402f4dd3a4343a1fb32200d05153012788bceb

**Comment by cescgina** [comment]
> Yeah, we don't need that as default (which is to redirect to a separate logging configuration file) . But there are more changes required. Please check [openstack-k8s-operators/ironic-operator@d9402f4](https://github.com/openstack-k8s-operators/ironic-operator/commit/d9402f4dd3a4343a1fb32200d05153012788bceb)

Thanks @rabi, I've updated the PR imitating the change you linked. Let me know if I missed anything.

**Review by abays — APPROVED** [review]
Looks like @rabi 's requested changes have been made

/lgtm

**Review by rabi — APPROVED** [review]

**Pull request merged**
