### PR TITLE
Pass all scorecard test except Status Block Exists

### PR DESCRIPTION
**Pull request by leifmadsen**
Related: https://github.com/openstack-k8s-operators/keystone-operator/issues/1

Passes all scorecard testing now except for the _Status Block Exists_ test, since no status information is provided by the controller (needs to be implemented).

### CODE REVIEW

**Comment by leifmadsen** [comment]
```
operator-sdk scorecard
INFO[0000] Using config file: /home/sysop/go/src/github.com/openstack-k8s-operators/keystone-operator/.osdk-scorecard.yaml 
basic:
	Spec Block Exists                   : pass
	Labels: 
		"necessity":"required"
		"suite":"basic"
		"test":"checkspectest"

	Status Block Exists                 : fail
	Labels: 
		"necessity":"required"
		"suite":"basic"
		"test":"checkstatustest"
	Suggestions: 
		Add a 'status' field to your Custom Resource

	Writing into CRs has an effect      : pass
	Labels: 
		"necessity":"required"
		"suite":"basic"
		"test":"writingintocrshaseffecttest"

olm:
	Status fields with descriptors      : pass
	Labels: 
		"necessity":"required"
		"suite":"olm"
		"test":"statusdescriptorstest"

	Bundle Validation Test              : pass
	Labels: 
		"test":"bundlevalidationtest"
		"necessity":"required"
		"suite":"olm"
	Log:
		time="2020-03-24T12:59:24-04:00" level=info msg="loading Bundles" dir=deploy/olm-catalog/keystone-operator/0.0.1/metadata
time="2020-03-24T12:59:24-04:00" level=info msg=directory dir=deploy/olm-catalog/keystone-operator/0.0.1/metadata file=metadata load=bundles
time="2020-03-24T12:59:24-04:00" level=info msg="loading Packages and Entries" dir=deploy/olm-catalog/keystone-operator/0.0.1/metadata
time="2020-03-24T12:59:24-04:00" level=info msg=directory dir=deploy/olm-catalog/keystone-operator/0.0.1/metadata file=metadata load=package


	Provided APIs have validation       : pass
	Labels: 
		"necessity":"required"
		"suite":"olm"
		"test":"crdshavevalidationtest"

	Owned CRDs have resources listed    : pass
	Labels: 
		"necessity":"required"
		"suite":"olm"
		"test":"crdshaveresourcestest"

	Spec fields with descriptors        : pass
	Labels: 
		"necessity":"required"
		"suite":"olm"
		"test":"specdescriptorstest"
```

**Comment by dprince** [comment]
Hi @leifmadsen so I tried pulling this a few weeks ago and got it partially working. The OLM part doesn't work as we now generate our CSV via a golang csv-generator. So I think we'd have to integrate that into running the scorecard tests for the CSV part to work correctly. If its okay I may just rebase it to do the non-OLM scorecard tests and then I think we can land it

**Comment by leifmadsen** [comment]
Heh, this is pretty old now, so I'm not surprised it's significantly out of date.

Why do you have a custom CSV generator?

**Comment by dprince** [comment]
> Why do you have a custom CSV generator?

I tried using operator-sdk's CSV generator. It seemed a bit rough around the edges (had some issues with substitution, etc.) Ended up just modeling it after kubevirts generators w/ golang.

**Comment by leifmadsen** [comment]
> > Why do you have a custom CSV generator?
> 
> I tried using operator-sdk's CSV generator. It seemed a bit rough around the edges (had some issues with substitution, etc.) Ended up just modeling it after kubevirts generators w/ golang.

Have you tried a newer version of operator-sdk? Lots of other Operators are using the CSV generator from there. It seems heavy handed to build a new set of tooling :) I can't imagine that'll be easily supportable going forward.

**Comment by dprince** [comment]
> Have you tried a newer version of operator-sdk? Lots of other Operators are using the CSV generator from there. It seems heavy handed to build a new set of tooling :) I can't imagine that'll be easily supportable going forward.

I have tried it. The command used to be called 'operator-sdk olm-catalog gen-csv', then it moved to 'operator-sdk generate csv'. And with the most recent SDK it seems to be gone entirely. Do you have examples of the operators using it. I reviewed what I could find extensively and the operator-sdk support for CSV generation seemed really a moving target at best. Ultimately I went with what I knew was a sure bet and based it off of a product that is organized very similar to what we'll end up with (multiple operators deployed under a single CSV)

**Pull request closed without merging**
