### PR TITLE
Do not delete KeystoneService with associated KeystoneEndpoint

### PR DESCRIPTION
**Pull request by kajinamit**
The KeystoneEndpoint CR is dependent on the KeystoneService CR, because keystone endpoints requires that the target service is created in advance.

This adds the finalizer to avoid removing KeystoneService before all associated KeystoneEndpoint instances are deleted.

### CODE REVIEW

**Comment by kajinamit** [comment]
/test keystone-operator-build-deploy-kuttl

The issue with Galera assertion is supposed to be fixed now.

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
