### PR TITLE
DNM: testing #363 with temporary replace lines

### PR DESCRIPTION
**Pull request by gibizer**

### CODE REVIEW

**Comment by gibizer** [comment]
Envtest is failing with the new dependencies. Probably due to mariadb changes that needs adaptation first.

```
Summarizing 16 Failures:
  [FAIL] Keystone controller when Deployment is completed [BeforeEach] should create a CronJob for trust flush
  /go/pkg/mod/github.com/bshephar/lib-common/modules/common@v0.0.0-20240205000728-69fddd97f72e/test/helpers/job.go:34
  [FAIL] Keystone controller when Deployment is completed [BeforeEach] should create a ConfigMap and Secret for client config
  /go/pkg/mod/github.com/bshephar/lib-common/modules/common@v0.0.0-20240205000728-69fddd97f72e/test/helpers/job.go:34
  [FAIL] Keystone controller when A KeystoneAPI is created with service override [BeforeEach] registers LoadBalancer services keystone endpoints
  /go/pkg/mod/github.com/bshephar/lib-common/modules/common@v0.0.0-20240205000728-69fddd97f72e/test/helpers/job.go:34
  [FAIL] Keystone controller when DB is created [It] should have db ready condition
  /go/pkg/mod/github.com/bshephar/lib-common/modules/common@v0.0.0-20240205000728-69fddd97f72e/test/helpers/conditions.go:53
  [FAIL] Keystone controller when DB sync is completed [BeforeEach] should have db sync ready condition and expose service ready condition
  /go/pkg/mod/github.com/bshephar/lib-common/modules/common@v0.0.0-20240205000728-69fddd97f72e/test/helpers/job.go:34
  [FAIL] Keystone controller when Bootstrap is completed [BeforeEach] should have bootstrap ready condition
  /go/pkg/mod/github.com/bshephar/lib-common/modules/common@v0.0.0-20240205000728-69fddd97f72e/test/helpers/job.go:34
  [FAIL] Keystone controller when A KeystoneAPI is created with service override endpointURL set [BeforeEach] registers endpointURL as public keystone endpoint
  /go/pkg/mod/github.com/bshephar/lib-common/modules/common@v0.0.0-20240205000728-69fddd97f72e/test/helpers/job.go:34
  [FAIL] Keystone controller when A KeystoneAPI is created with service override [BeforeEach] creates LoadBalancer service
  /go/pkg/mod/github.com/bshephar/lib-common/modules/common@v0.0.0-20240205000728-69fddd97f72e/test/helpers/job.go:34
  [FAIL] Keystone controller when Deployment is completed [BeforeEach] should have deployment ready condition and cronjob ready condition
  /go/pkg/mod/github.com/bshephar/lib-common/modules/common@v0.0.0-20240205000728-69fddd97f72e/test/helpers/job.go:34
  [FAIL] Keystone controller when A KeystoneAPI is created with TLS [It] it creates dbsync job with CA certs mounted
  /go/pkg/mod/github.com/bshephar/lib-common/modules/common@v0.0.0-20240205000728-69fddd97f72e/test/helpers/job.go:34
  [FAIL] Keystone controller when A KeystoneAPI is created with TLS [It] it creates bootstrap job with CA certs mounted
  /go/pkg/mod/github.com/bshephar/lib-common/modules/common@v0.0.0-20240205000728-69fddd97f72e/test/helpers/job.go:34
  [FAIL] Keystone controller when A KeystoneAPI is created with TLS [It] it creates deployment with CA and service certs mounted
  /go/pkg/mod/github.com/bshephar/lib-common/modules/common@v0.0.0-20240205000728-69fddd97f72e/test/helpers/job.go:34
  [FAIL] Keystone controller when A KeystoneAPI is created with TLS [It] registers endpointURL as public keystone endpoint
  /go/pkg/mod/github.com/bshephar/lib-common/modules/common@v0.0.0-20240205000728-69fddd97f72e/test/helpers/job.go:34
  [FAIL] Keystone controller when A KeystoneAPI is created with TLS [It] reconfigures the keystone pod when CA changes
  /go/pkg/mod/github.com/bshephar/lib-common/modules/common@v0.0.0-20240205000728-69fddd97f72e/test/helpers/job.go:34
  [FAIL] Keystone controller when Deployment is completed [BeforeEach] should create a Deployment
  /go/pkg/mod/github.com/bshephar/lib-common/modules/common@v0.0.0-20240205000728-69fddd97f72e/test/helpers/job.go:34
  [FAIL] Keystone controller when A KeystoneAPI is created with TLS and service override endpointURL set [BeforeEach] registers endpointURL as public keystone endpoint
  /go/pkg/mod/github.com/bshephar/lib-common/modules/common@v0.0.0-20240205000728-69fddd97f72e/test/helpers/job.go:34
```

**Comment by stuggi** [comment]
@gibizer I hit the same when working on db tls integration. envtest update is required https://github.com/openstack-k8s-operators/keystone-operator/pull/366

**Comment by bshephar** [comment]
Just want CI to run the functional tests so that we can capture the results here for posterity.

**Pull request closed without merging**
